# Generated by Django 5.1 on 2025-03-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'dollor'), ('UZS', 'So`m'), ('EUR', 'euro')], default='USD', max_length=3),
        ),
    ]
