# Generated by Django 5.1.7 on 2025-04-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.SmallIntegerField(),
        ),
    ]
